### ISSUE TITLE
neila - Users can't set the future epoch

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-astaria-judging#134]
neila

medium

# Users can't set the future epoch

## Summary
Users can't set the future epoch

## Vulnerability Detail
Docs says as follows
https://docs.astaria.xyz/docs/smart-contracts/WithdrawProxy
> liquidity providers must signal that they wish to withdraw funds at least one epoch in advance.
However, `currentEpoch` is hardcoded

## Impact 
Users can't set future epoch for withdrawal

## Code Snippet
https://github.com/unchain-dev/2022-10-astaria-UNCHAIN/blob/main/src/PublicVault.sol#L123
```solidity
uint64 public currentEpoch = 0;
```
https://github.com/unchain-dev/2022-10-astaria-UNCHAIN/blob/main/src/PublicVault.sol#L161-L168
```solidity

function withdraw(
    uint256 assets,
    address receiver,
    address owner
  ) public virtual override returns (uint256 shares) {
    shares = previewWithdraw(assets);
    redeemFutureEpoch(shares, receiver, owner, currentEpoch);
  }
```
https://github.com/unchain-dev/2022-10-astaria-UNCHAIN/blob/main/src/PublicVault.sol#L178-L199
```solidity
function redeemFutureEpoch(
    uint256 shares,
    address receiver,
    address owner,
    uint64 epoch
  ) public virtual returns (uint256 assets) {
    // check to ensure that the requested epoch is not the current epoch or in the past
    // always epoch == currentEpoch by redeem

    require(epoch >= currentEpoch, "Exit epoch too low");
    require(msg.sender == owner, "Only the owner can redeem");
    // check for rounding error since we round down in previewRedeem.
```

## Tool used
Manual Review

## Recommendation
Let users to be able to set epoch

**Comment by IAmTurnipBoy** [comment]
Escalate for 1 USDC

Invalid. Current epoch only hard-coded on redeem/withdraw. User can call redeemFutureEpoch to redeem on any epoch they want as long is it's after current epoch.

**Comment by sherlock-admin** [comment]
> Escalate for 1 USDC
> 
> Invalid. Current epoch only hard-coded on redeem/withdraw. User can call redeemFutureEpoch to redeem on any epoch they want as long is it's after current epoch.

You've created a valid escalation for 1 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Evert0x** [comment]
Escalation accepted

**Comment by sherlock-admin** [comment]
> Escalation accepted

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
