### ISSUE TITLE
neila - Can't call this function before epoch ended

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-astaria-judging#136]
neila

medium

# Can't call this function before epoch ended

## Summary
Can't call this function before epoch ended
found by [Tomosuke0930](https://github.com/Tomosuke0930)

## Vulnerability Detail
The comment says as follows
https://github.com/unchain-dev/2022-10-astaria-UNCHAIN/blob/main/src/PublicVault.sol#L236-L238
```solidity
/**
  * @notice Rotate epoch boundary. This must be called before the next epoch can begin.
*/
```
However, this function can call the after `currentEpoch` ended
```solidity
require(getEpochEnd(currentEpoch)  < block.timestamp, "Epoch has not ended");
```
## Impact
If the `currentEpoch` is 3.
`getEpochEnd(currentEpoch)` will be as follows.
```solidity
START() + 4 * EPOCH_LENGTH()
```
And block.timestamp has to be bigger than this value to pass this check. Therefore, this function can call when the epoch enters into 4.

## Code Snippet
https://github.com/unchain-dev/2022-10-astaria-UNCHAIN/blob/main/src/PublicVault.sol#L236-L249
```solidity
  /**
   * @notice Rotate epoch boundary. This must be called before the next epoch can begin.
   */
  function processEpoch() external {
    // check to make sure epoch is over
    require(getEpochEnd(currentEpoch) < block.timestamp, "Epoch has not ended");
    require(withdrawReserve == 0, "Withdraw reserve not empty");
    if (liquidationAccountants[currentEpoch] != address(0)) {
      require(
        LiquidationAccountant(liquidationAccountants[currentEpoch])
          .getFinalAuctionEnd() < block.timestamp,
        "Final auction not ended"
      );
    }
```
https://github.com/unchain-dev/2022-10-astaria-UNCHAIN/blob/main/src/PublicVault.sol#L473-L475
```solidity
function getEpochEnd(uint256 epoch) public view returns (uint256) {
    return START() + (epoch + 1) * EPOCH_LENGTH();
}

```

## Tool used
Manual Review

## Recommendation
Should change as follows to implement like the comment.
```solidity
/**
 * @notice Rotate epoch boundary. This must be called before the next epoch can begin.
*/
function processEpoch() external {
 // check to make sure epoch is over
 require(getEpochEnd(currentEpoch - 1) < block.timestamp, "Epoch has not ended");
  /* ... */
}
```

**Comment by IAmTurnipBoy** [comment]
Escalate for 1 USDC

Invalid. getEpochEnd is math is already correct. Epochs start at 0 not 1 so you need to add 1 or else you're end time will be 1 epoch behind. As an example, epoch 0 ends after 1 x epochLength, so to find the end you have to add one to the epoch (0 + 1 = 1), epoch 1 ends after 2 x epochLength, etc.

**Comment by sherlock-admin** [comment]
> Escalate for 1 USDC
> 
> Invalid. getEpochEnd is math is already correct. Epochs start at 0 not 1 so you need to add 1 or else you're end time will be 1 epoch behind. As an example, epoch 0 ends after 1 x epochLength, so to find the end you have to add one to the epoch (0 + 1 = 1), epoch 1 ends after 2 x epochLength, etc. 

You've created a valid escalation for 1 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Evert0x** [comment]
Escalation accepted

**Comment by sherlock-admin** [comment]
> Escalation accepted

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
