### ISSUE TITLE
TurnipBoy - PublicVault.sol doesn't override ERC4626Cloned.sol#mint allowing users to bypass router control of depositing

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-astaria-judging#155]
TurnipBoy

high

# PublicVault.sol doesn't override ERC4626Cloned.sol#mint allowing users to bypass router control of depositing

## Summary

`PublicVault.sol#deposit` specifically limits depositing to the `AstariaRouter.sol`. It inherits from `ERC4626Cloned` but never overrides the `mint` function, allowing users to directly mint with to the vault instead of through the `AstariaRouter.sol`.

## Vulnerability Detail

PublicVault.sol - PublicVault

    function deposit(uint256 amount, address receiver)
      public
      override(Vault, ERC4626Cloned)
      whenNotPaused
      returns (uint256)
    {
      return super.deposit(amount, receiver);
    }

PublicVault.sol - Vault

    function deposit(uint256 amount, address)
      public
      virtual
      override
      returns (uint256)
    {
      require(msg.sender == owner(), "only the appraiser can fund this vault");
      ERC20(underlying()).safeTransferFrom(
        address(msg.sender),
        address(this),
        amount
      );
      return amount;
    }

`Vault#deposit` requires that the caller is the router. `ERC4626Cloned.sol#mint` accomplishes a similar goal to `deposit` but called with the number of shares instead of the amount of assets. `Deposit` is locked only to be accessed by the router but the sponsors forgot to override `mint` allowing users to directly mint to `PublicVault.sol`. This can lead to a large number of problems given how shares are valued. It can cause shares to be minted for unintended prices which can harm both current or minting users.

## Impact

Users can bypass router only minting, potentially causing loss of funds for themselves or current vault share holders 

## Code Snippet

https://github.com/sherlock-audit/2022-10-astaria/blob/main/src/PublicVault.sol#L78-L91

## Tool used

Manual Review

## Recommendation

Override `mint` to disable it or to limit call only to the router contract.

Duplicate of #174

**Comment by IAmTurnipBoy** [comment]
Escalate for 1 USDC

Not a dupe of #176. Actually a dupe of #174. Both discuss the underlying issue that ERC4626Cloned::Mint isn't overriden in publicVault

**Comment by sherlock-admin** [comment]
> Escalate for 1 USDC
> 
> Not a dupe of #176. Actually a dupe of #174. Both discuss the underlying issue that ERC4626Cloned::Mint isn't overriden in publicVault

You've created a valid escalation for 1 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Evert0x** [comment]
Escalation accepted

**Comment by sherlock-admin** [comment]
> Escalation accepted

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
