### ISSUE TITLE
ctf_sec - Lack of access control in CollateralToken#onERC721Received hook

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-astaria-judging#156]
ctf_sec

medium

# Lack of access control in CollateralToken#onERC721Received hook

## Summary

Lack of access control in CollateralToken#onERC721Received hook allows anyone to call the function 

## Vulnerability Detail

The function onERC721Received is lack of access control.

https://github.com/sherlock-audit/2022-10-astaria/blob/main/src/CollateralToken.sol#L259-L271

while the comment quotes

```solidity
* @param operator_ the approved sender that called safeTransferFrom
```

such authorization is not implemented in the code.

## Impact

The right way to use the onERC721Received is 

https://github.com/sherlock-audit/2022-10-astaria/blob/main/src/AstariaRouter.sol#L578-L586

but onERC721Received is called either from ERC721 safeTransfer or safeMint

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/d5ca39e9a264ddcadd5742484b6d391ae1647a10/contracts/token/ERC721/ERC721.sol#L429 (safe for solmate)

```solidity
    function _checkOnERC721Received(
        address from,
        address to,
        uint256 tokenId,
        bytes memory data
    ) private returns (bool) {
        if (to.isContract()) {
            try IERC721Receiver(to).onERC721Received(_msgSender(), from, tokenId, data) returns (bytes4 retval) {
                return retval == IERC721Receiver.onERC721Received.selector;
            } catch (bytes memory reason) {
                if (reason.length == 0) {
                    revert("ERC721: transfer to non ERC721Receiver implementer");
                } else {
                    /// @solidity memory-safe-assembly
                    assembly {
                        revert(add(32, reason), mload(reason))
                    }
                }
            }
        } else {
            return true;
        }
    }
```

or basically, anyone can his hook function to create the invalid collateral token position.

## Code Snippet

https://github.com/sherlock-audit/2022-10-astaria/blob/main/src/CollateralToken.sol#L259-L271

https://github.com/sherlock-audit/2022-10-astaria/blob/main/src/AstariaRouter.sol#L578-L588

## Tool used

Manual Review

## Recommendation

We recommend the project valid the msg.sender in CollateralToken#onERC721Received function

**Comment by ctf-sec** [comment]
Escalated for 1 USDC.

https://github.com/sherlock-audit/2022-10-astaria/blob/main/src/CollateralToken.sol#L259-L271

```solidity
  /**
   * @dev Mints a new CollateralToken wrapping an NFT.
   * @param operator_ the approved sender that called safeTransferFrom
   * @param from_ the owner of the collateral deposited
   * @param data_ calldata that is apart of the callback
   * @return a static return of the receive signature
   */
  function onERC721Received(
    address operator_,
    address from_,
    uint256 tokenId_,
    bytes calldata data_
  ) external override returns (bytes4) {
```

Anyone can call this function to Mints a new CollateralToken multiple times.
