### ISSUE TITLE
yixxas - `auctionExists()` is implemented in an unreliable way as an auction can exist but fail the check

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-astaria-judging#164]
yixxas

medium

# `auctionExists()` is implemented in an unreliable way as an auction can exist but fail the check

## Summary
`auctionExists()` checks if an auction exist by checking if `auctions[tokenId].initiator != address(0)`. This is problematic as an auction can be created with `auctions[tokenId].initiator = address(0)` which bypasses this check.

## Vulnerability Detail
`auctionExists()` is used multiple times in both `CollateralToken.sol` and `LienToken.sol`. It is important that the function returns an accurate result. For example, `createLien()` can only be called if an auction exist, but in the case when `auctions[tokenId].initiator == address(0)`, this will revert even though auction is already created.

## Impact
Multiple parts of the protocol will not be able to function due to a wrong return result from `auctionExists()`.

## Code Snippet
https://github.com/sherlock-audit/2022-10-astaria/blob/main/lib/astaria-gpl/src/AuctionHouse.sol#L67-L85
https://github.com/sherlock-audit/2022-10-astaria/blob/main/lib/astaria-gpl/src/AuctionHouse.sol#L318-L321

## Tool used

Manual Review

## Recommendation
To fix this, we can either ensure that `initiator` cannot be the 0 address, or we can use a more reliable check - `auctions[tokenId].firstBidTime != 0`, since `firstBidTime` is always set to `block.timestamp`.

However, I recommend that both of these are implemented as `initiator` should not be the 0 address as mentioned in my other issue #8.

**Comment by IAmTurnipBoy** [comment]
Escalate for 1 USDC

Invalid submission. Initiator can never be address(0). AuctionVault can only be called by the router which always uses msg.sender as initiator. Unless address(0) is the msg.sender who calls liquidate on Astaria router this is impossible.

Auctionhouse::createAuction only allows CollateralToken to call it via requiresAuth modifier:
https://github.com/sherlock-audit/2022-10-astaria/blob/7d12a5516b7c74099e1ce6fb4ec87c102aec2786/lib/astaria-gpl/src/AuctionHouse.sol#L72

CollateralToken::auctionVault only allows AstariaRouter to call via requiresAuth modifier:
https://github.com/sherlock-audit/2022-10-astaria/blob/7d12a5516b7c74099e1ce6fb4ec87c102aec2786/src/CollateralToken.sol#L314

AstariaRouter only ever calls auctionVault with msg.sender:
https://github.com/sherlock-audit/2022-10-astaria/blob/7d12a5516b7c74099e1ce6fb4ec87c102aec2786/src/AstariaRouter.sol#L419-L423

**Comment by sherlock-admin** [comment]
> Escalate for 1 USDC
> 
> Invalid submission. Initiator can never be address(0). AuctionVault can only be called by the router which always uses msg.sender as initiator. Unless address(0) is the msg.sender who calls liquidate on Astaria router this is impossible.
> 
> Auctionhouse::createAuction only allows CollateralToken to call it via requiresAuth modifier:
> https://github.com/sherlock-audit/2022-10-astaria/blob/7d12a5516b7c74099e1ce6fb4ec87c102aec2786/lib/astaria-gpl/src/AuctionHouse.sol#L72
> 
> CollateralToken::auctionVault only allows AstariaRouter to call via requiresAuth modifier:
> https://github.com/sherlock-audit/2022-10-astaria/blob/7d12a5516b7c74099e1ce6fb4ec87c102aec2786/src/CollateralToken.sol#L314
> 
> AstariaRouter only ever calls auctionVault with msg.sender:
> https://github.com/sherlock-audit/2022-10-astaria/blob/7d12a5516b7c74099e1ce6fb4ec87c102aec2786/src/AstariaRouter.sol#L419-L423

You've created a valid escalation for 1 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Evert0x** [comment]
Escalation accepted

**Comment by sherlock-admin** [comment]
> Escalation accepted

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
