### ISSUE TITLE
ak1 - Borrower can not take five loans as per what the astaria protocol says.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-astaria-judging#165]
ak1

medium

# Borrower can not take five loans as per what the astaria protocol says.

## Summary

Borrower can not take five loans as per what the astaria protocol says.
due to logical issue, a borrower can take maximum four loans only.

## Vulnerability Detail

https://docs.astaria.xyz/docs/threeactors#:~:text=A%20borrower%20can%20take%20up%20to%205%20loans%20against%20the%20same%20NFT%2C%20provided%20that%20the%20maximum%20potential%20debt%20that%20could%20be%20accrued%20by%20their%20loans%20does%20not%20exceed%20a%20maximum%20potential%20debt%20value%20set%20by%20the%20strategist.

As per the astaria ptocol, an NFT owner can take maximum five loans. The number of loans can be attributed to number of liens token issued.

https://github.com/sherlock-audit/2022-10-astaria/blob/main/src/LienToken.sol#L60

There is a condition check in lien token issuance where it check the array lenght incorrectly to fix the number of lien tokens.

https://github.com/sherlock-audit/2022-10-astaria/blob/main/src/LienToken.sol#L281-L285

## Impact

Can not issue all the five loans as per the protocol.
Protocol may loose the benefit of fee and other advanatages that could be gained by valid borrower who pays on time.

## Code Snippet

https://github.com/sherlock-audit/2022-10-astaria/blob/main/src/LienToken.sol#L281-L285

## Tool used

Manual Review

## Recommendation

change the condition check as less then or equal.

require(
      uint256(liens[collateralId].length) <= MAX_LIENS,
      "too many liens active"
    );

**Comment by aktech297** [comment]
I am escalating this for 2 USDC.
I believe this issue is misjudged.  
It is issue .. as per protocol document a borrower can be allowed to take 5 loans. But the current conditional logic allows to take 4 loans only.

**Comment by aktech297** [comment]
Escalate for 2 USDC
I believe this issue is misjudged.
It is issue .. as per protocol document a borrower can be allowed to take 5 loans. But the current conditional logic allows to take 4 loans only.

**Comment by sherlock-admin** [comment]
> Escalate for 2 USDC
> I believe this issue is misjudged.
> It is issue .. as per protocol document a borrower can be allowed to take 5 loans. But the current conditional logic allows to take 4 loans only.

You've created a valid escalation for 2 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by zobront** [comment]
@aktech297 I believe this check happens before adding the newest lien, so it's correctly capping it at five. If you walk through the logic of taking a 5th lien, I think you'll see it is allowed to be added.

**Comment by Evert0x** [comment]
Escalation rejected

This check happens before the lien is added, so checking that it's <= 4 correctly caps it to 5.

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> This check happens before the lien is added, so checking that it's <= 4 correctly caps it to 5.

This issue's escalations have been rejected!

Contestants' payouts and scores will be updated according to the changes made on this issue.
