### ISSUE TITLE
0xRajeev - Incorrect operator in `AstariaRouter.isValidRefinance` can lead to borrower loss and potential liquidation

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-astaria-judging#168]
0xRajeev

high

# Incorrect operator in `AstariaRouter.isValidRefinance` can lead to borrower loss and potential liquidation

## Summary

Incorrect use of operator `>=` instead of `<=` in `isValidRefinance()` can lead to borrower loss and potential liquidation.

## Vulnerability Detail

The check in `isValidRefinance()` for `newLien.rate >= minNewRate` is incorrect because it allows the new lien's rate of interest to be greater than maximum new rate instead of it being lesser than that value. The calculation of `uint256(lien.rate) - minInterestBPS;` actually gives `maxNewRate` and not `minNewRate`.

## Impact

Refinancing is a crucial feature of the protocol to allow a borrower to refinance their loan if a certain minimum improvement of interest rate or duration is offered. This logical error allows a borrower to accidentally refinance or a malicious strategist to intentionally refinance an existing loan to a new one with a worse interest rate, leading to material loss for the borrower and potential liquidation in future.

## Code Snippet

1. https://github.com/sherlock-audit/2022-10-astaria/blob/main/src/AstariaRouter.sol#L482-L491
2. https://github.com/sherlock-audit/2022-10-astaria/blob/main/src/AstariaRouter.sol#L106
3. https://docs.astaria.xyz/docs/protocol-mechanics/refinancing

## Tool used

Manual Review

## Recommendation

Change `>=` to `<=` in `newLien.rate >= minNewRate` in the return statement on L488.

**Comment by IAmTurnipBoy** [comment]
Escalate for 1 USDC

Duplicate of #21, just like #21 I disagree with severity because it would require external factors to cause loss

**Comment by sherlock-admin** [comment]
> Escalate for 1 USDC
> 
> Duplicate of #21, just like #21 I disagree with severity because it would require external factors to cause loss

You've created a valid escalation for 1 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Evert0x** [comment]
Escalation accepted

**Comment by sherlock-admin** [comment]
> Escalation accepted

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
