### ISSUE TITLE
0xRajeev - Auctions with remaining liens will always revert causing loss of funds for the highest bidder and stuck collateral

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-astaria-judging#185]
0xRajeev

high

# Auctions with remaining liens will always revert causing loss of funds for the highest bidder and stuck collateral

## Summary

Auctions with remaining liens can never be ended because they will revert.

## Vulnerability Detail

Function `endAuction` will always revert with `NOT_MINTED` error if there are any `liensRemaining` because the value passed to `LIEN_TOKEN.ownerOf` is `i` in the for loop instead of `liensRemaining[i]`.

## Impact

Auctions with remaining liens can never be ended leading to loss of funds for the highest bidder and stuck collateral.
 
## Code Snippet

1. https://github.com/sherlock-audit/2022-10-astaria/blob/main/lib/astaria-gpl/src/AuctionHouse.sol#L194-L201

## Tool used

Manual Review

## Recommendation

Pass `liensRemaining[i]` to `LIEN_TOKEN.ownerOf`.

**Comment by IAmTurnipBoy** [comment]
Escalate for 1 USDC

Is a duplicate of #259. Same issue described with same resolution

**Comment by sherlock-admin** [comment]
> Escalate for 1 USDC
> 
> Is a duplicate of #259. Same issue described with same resolution

You've created a valid escalation for 1 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Evert0x** [comment]
Escalation accepted

**Comment by sherlock-admin** [comment]
> Escalation accepted

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
