### ISSUE TITLE
Bnke0x0 - deposit() and  mint() functions do not work

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-astaria-judging#2]
Bnke0x0

high

# deposit() and  mint() functions do not work

## Impact
The `ERC4626-Cloned` contract inherits from the `ERC20Cloned` and `ERC4626Base` contracts. When the user calls the deposit and mint functions of the  `ERC4626-Cloned` contract, the deposit and mint functions of the `ERC20Cloned` or  `ERC4626Base` contracts are called.

The deposit and mint functions of the `ERC20Cloned` or  `ERC4626Base` contracts will call the deposit and mint functions of the `ERC4626-Cloned` contract. The `ERC4626-Cloned` contract inherits from the ERC4626 contract, that is, the deposit and mint functions of the ERC4626 contract will be called.

The deposit and mint functions of the ERC4626 contract will call the safeTransferFrom function. Since the caller is the  `ERC4626-Cloned` contract, msg.sender will be the  `ERC4626-Cloned` contract. And because the user calls the deposit and mint functions of the  `ERC4626-Cloned` contract without transferring tokens to the  `ERC4626-Cloned` contract and approving the call will fail.

## Code Snippet
https://github.com/sherlock-audit/2022-10-astaria/blob/main/lib/astaria-gpl/src/ERC4626-Cloned.sol#L305-L322
      
              `  function deposit(uint256 assets, address receiver)
                 public
                  virtual
                  override(IVault)
                  returns (uint256 shares)
                {
                  // Check for rounding error since we round down in previewDeposit.
                  require((shares = previewDeposit(assets)) != 0, "ZERO_SHARES");

                  // Need to transfer before minting or ERC777s could reenter.
                  ERC20(underlying()).safeTransferFrom(msg.sender, address(this), assets);

                  _mint(receiver, shares);

                  emit Deposit(msg.sender, receiver, assets, shares);

                  afterDeposit(assets, shares);
                }`

https://github.com/sherlock-audit/2022-10-astaria/blob/main/lib/astaria-gpl/src/ERC4626-Cloned.sol#L324-L339
      
              `   function mint(uint256 shares, address receiver)
                  public
                 virtual
                 returns (uint256 assets)
               {
                 assets = previewMint(shares); // No need to check for rounding error, previewMint rounds up.

                 // Need to transfer before minting or ERC777s could reenter.
                ERC20(underlying()).safeTransferFrom(msg.sender, address(this), assets);

                 _mint(receiver, shares);

                 emit Deposit(msg.sender, receiver, assets, shares);

                 afterDeposit(assets, shares);
               }`

## Tool used

Manual Review

## Recommendation
In the deposit and mint functions of the `ERC4626-Cloned` contract, add code for the user to transfer tokens and approve the use of tokens in the Astaria contract.

**Comment by IAmTurnipBoy** [comment]
Escalate for 1 USDC

This report is invalid. msg.sender doesn't change when a contract calls an inherited function

**Comment by sherlock-admin** [comment]
> Escalate for 1 USDC
> 
> This report is invalid. msg.sender doesn't change when a contract calls an inherited function

You've created a valid escalation for 1 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Evert0x** [comment]
Escalation accepted

**Comment by sherlock-admin** [comment]
> Escalation accepted

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
