### ISSUE TITLE
cryptphi - Any User can request loans for without depositing collateral

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-astaria-judging#212]
cryptphi

high

# Any User can request loans for without depositing collateral

## Summary
The VaultImplementation.commitToLien() function allows any user to take loans on collateral token, this allows users to take loans on collateral tokens by calling the contract directly instead of through the AstariaRouter contract.

## Vulnerability Detail
In the call to commitToLien in a private Vault, any user is able to request for a loan on collateral token, this allows users to take loans on collateral tokens. However a user can mint collateral tokens without depositing any asset in the CollateralToken contract. The user can simply have a contract call the CollateralToken.onERC721Received() without any transfer to the collateraltoken contract, be issued a collateralToken and then call the private vault's commitToLien() to take a loan instead of making the call through AstariaRouter.

## Impact
Loss of funds

## Code Snippet
https://github.com/sherlock-audit/2022-10-astaria/blob/main/src/CollateralToken.sol#L266-L296
https://github.com/sherlock-audit/2022-10-astaria/blob/main/src/VaultImplementation.sol#L242-L258

## Tool used
Manual Review

## Recommendation
If necessary, apply access control access on VaultImplementation.commitToLien() to be called by the Router only.

**Comment by cryptphitraining** [comment]
Escalate for 10 USDC

@zobront Please provide context on the dispute. 

The issue above depicts how easy it is to mint a collateral token from the Collateral contract. And with properly crafted input, the malicious user can then create a valid new lien against a CollateralToken, before proceeding to eventually call commitToLien with user controlled crafted inputs

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> @zobront Please provide context on the dispute. 
> 
> The issue above depicts how easy it is to mint a collateral token from the Collateral contract. And with properly crafted input, the malicious user can then create a valid new lien against a CollateralToken, before proceeding to eventually call commitToLien with user controlled crafted inputs

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Evert0x** [comment]
Escalation rejected

This isn't a problem, because strategists won't be accepting the random NFT as collateral.

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> This isn't a problem, because strategists won't be accepting the random NFT as collateral.

This issue's escalations have been rejected!

Watsons who escalated this issue will have their escalation amount deducted from their next payout.
