### ISSUE TITLE
hansfriese - `AuctionHouse.createBid()` doesn't handle incoming payments properly.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-astaria-judging#223]
hansfriese

high

# `AuctionHouse.createBid()` doesn't handle incoming payments properly.

## Summary
`AuctionHouse.createBid()` doesn't handle incoming payments properly.

## Vulnerability Detail
`AuctionHouse.createBid()` is used to receive bids from users and it refunds the last bidder when there is a new bidder with a higher bid amount.

But it doesn't handle the incoming payment for the new bidder [here](https://github.com/sherlock-audit/2022-10-astaria/blob/main/lib/astaria-gpl/src/AuctionHouse.sol#L118).

```solidity
    if (firstBidTime == 0) {
      auctions[tokenId].firstBidTime = block.timestamp.safeCastTo64();
    } else if (lastBidder != address(0)) {
      uint256 lastBidderRefund = amount - vaultPayment;
      _handleOutGoingPayment(lastBidder, lastBidderRefund);
    }

    _handleIncomingPayment(tokenId, vaultPayment, address(msg.sender)); //@audit vaultPayment => amount
```

It should request the whole `amount` but `amount - currentBid` now.

## Impact
`AuctionHouse.createBid()` requests a smaller amount than it should from the second bidder so the auction house protocol is lack funds.

## Code Snippet
https://github.com/sherlock-audit/2022-10-astaria/blob/main/lib/astaria-gpl/src/AuctionHouse.sol#L118

## Tool used
Manual Review

## Recommendation
It should request the whole amount like below.

```solidity
    _handleIncomingPayment(tokenId, amount, address(msg.sender));
```

**Comment by IAmTurnipBoy** [comment]
Escalate for 1 USDC

Issue is invalid. It does correctly handle bids. Old bidder is refunded by msg.sender. If you use amount for the incoming payment it would double charge msg.sender. Contract is working correctly already, as dev has stated

Assume 10 WETH bid with prior bid of 6 WETH. vaultPayment = 10 - 6 = 4. lastBidderRefund = 10 - 4 = 6. This correctly refunds 6 WETH to the previous bidder and 4 WETH goes to paying off liens.

**Comment by sherlock-admin** [comment]
> Escalate for 1 USDC
> 
> Issue is invalid. It does correctly handle bids. Old bidder is refunded by msg.sender. If you use amount for the incoming payment it would double charge msg.sender. Contract is working correctly already, as dev has stated
> 
> Assume 10 WETH bid with prior bid of 6 WETH. vaultPayment = 10 - 6 = 4. lastBidderRefund = 10 - 4 = 6. This correctly refunds 6 WETH to the previous bidder and 4 WETH goes to paying off liens.

You've created a valid escalation for 1 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hansfriese** [comment]
As an author of this issue, I agree it's invalid. I've misunderstood one thing before and judges don't need to check again.

**Comment by Evert0x** [comment]
Escalation accepted

**Comment by sherlock-admin** [comment]
> Escalation accepted

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
