### ISSUE TITLE
obront - Checks for epoch lengths of new vaults are slightly off

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-astaria-judging#23]
obront

medium

# Checks for epoch lengths of new vaults are slightly off

## Summary

The check that new vaults has an `epochLength` in the range from `minEpochLength` (inclusive) to `maxEpochLength` (not inclusive) is slightly off.

## Vulnerability Detail

The error string for an incorrectly set epoch length reads:

> "epochLength must be greater than or equal to MIN_EPOCH_LENGTH and less than MAX_EPOCH_LENGTH"

However, in the code implementing this check, an `epochLength` equal to `maxEpochLength` is allowed.

```solidity
require(
  epochLength >= minEpochLength && epochLength <= maxEpochLength,
  "epochLength must be greater than or equal to MIN_EPOCH_LENGTH and less than MAX_EPOCH_LENGTH"
);
```

## Impact

Slightly longer epochs will be permitted than was intended.

## Code Snippet

https://github.com/sherlock-audit/2022-10-astaria/blob/main/src/AstariaRouter.sol#L509-L512

## Tool used

Manual Review

## Recommendation

Change the check in the require statement to match the intended behavior:

```solidity
require(
  epochLength >= minEpochLength && epochLength < maxEpochLength,
  "epochLength must be greater than or equal to MIN_EPOCH_LENGTH and less than MAX_EPOCH_LENGTH"
);
```

**Comment by IAmTurnipBoy** [comment]
Escalate for 1 USDC

Medium for the epoch being 1 second longer than limit? Seem generous unless you can provide a scenario this is damaging. Should be low.

**Comment by sherlock-admin** [comment]
> Escalate for 1 USDC
> 
> Medium for the epoch being 1 second longer than limit? Seem generous unless you can provide a scenario this is damaging. Should be low.

You've created a valid escalation for 1 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Evert0x** [comment]
Escalation accepted. Downgrading to low.

**Comment by sherlock-admin** [comment]
> Escalation accepted. Downgrading to low.

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
