### ISSUE TITLE
sorrynotsorry - LienToken's `calculateSlope` might panic

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-astaria-judging#235]
sorrynotsorry

medium

# LienToken's `calculateSlope` might panic

## Summary
LienToken's `calculateSlope` might panic
## Vulnerability Detail
LienToken's `calculateSlope` returns the computed rate for a specified lien.
However, the return is not validated against the linen's being active and the `last` value.

The function is as below;
```solidity
  function calculateSlope(uint256 lienId) public view returns (uint256) {
    Lien memory lien = lienData[lienId];
    uint256 end = (lien.start + lien.duration);
    uint256 owedAtEnd = _getOwed(lien, end);
    return (owedAtEnd - lien.amount).mulDivDown(1, end - lien.last);
  }
```
[Permalink](https://github.com/sherlock-audit/2022-10-astaria/blob/main/src/LienToken.sol#L440-L445)

If the lien is not active and the payout is executed at the `end` of the lien then `(end - lien.last)` will be 0 causing the function to panic.

## Impact
Incorrect accounting
## Code Snippet
```solidity
  function calculateSlope(uint256 lienId) public view returns (uint256) {
    Lien memory lien = lienData[lienId];
    uint256 end = (lien.start + lien.duration);
    uint256 owedAtEnd = _getOwed(lien, end);
    return (owedAtEnd - lien.amount).mulDivDown(1, end - lien.last);
  }
```
[Permalink](https://github.com/sherlock-audit/2022-10-astaria/blob/main/src/LienToken.sol#L440-L445)
## Tool used

Manual Review

## Recommendation
Validate accordingly;

```solidity
  function calculateSlope(uint256 lienId) public view returns (uint256) {
    Lien memory lien = lienData[lienId];
    require(lien.active,"err");
    uint256 end = (lien.start + lien.duration);
    require(end != lien.last,"err");
    uint256 owedAtEnd = _getOwed(lien, end);
    return (owedAtEnd - lien.amount).mulDivDown(1, end - lien.last);
  }
```

**Comment by IAmTurnipBoy** [comment]
Escalate for 1 USDC

Duplicate of #179. Same underlying problem in both. One points out the 0 case, the other points out the underflow after expiration.

Relevant lines:

https://github.com/sherlock-audit/2022-10-astaria/blob/7d12a5516b7c74099e1ce6fb4ec87c102aec2786/src/LienToken.sol#L607-L610

**Comment by sherlock-admin** [comment]
> Escalate for 1 USDC
> 
> Duplicate of #179. Same underlying problem in both. One points out the 0 case, the other points out the underflow after expiration.
> 
> Relevant lines:
> 
> https://github.com/sherlock-audit/2022-10-astaria/blob/7d12a5516b7c74099e1ce6fb4ec87c102aec2786/src/LienToken.sol#L607-L610

You've created a valid escalation for 1 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Evert0x** [comment]
Escalation accepted

**Comment by sherlock-admin** [comment]
> Escalation accepted

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
