### ISSUE TITLE
bin2chen - cancelAuction() can  cancel "the completed Auction"

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-astaria-judging#239]
bin2chen

medium

# cancelAuction() can  cancel "the completed Auction"

## Summary
AuctionHouse#cancelAuction() can  cancel "the completed Auction"

## Vulnerability Detail
When the auction has ended (time is up), and the bid amount is less than reservePrice, then it still can #cancel(), this does not make sense, after the end of the auction should only #endAuction()

## Impact
after the end of the auction should cancel

## Code Snippet
https://github.com/sherlock-audit/2022-10-astaria/blob/main/lib/astaria-gpl/src/AuctionHouse.sol#L210

```solidity
  function cancelAuction(uint256 auctionId, address canceledBy)
    external
    requiresAuth
  {
    require(
      auctions[auctionId].currentBid < auctions[auctionId].reservePrice,
      "cancelAuction: Auction is at or above reserve"
    );
  /**** only check price , no check if end ****/
```

## Tool used

Manual Review

## Recommendation
require not end
```solidity
  function cancelAuction(uint256 auctionId, address canceledBy)
    external
    requiresAuth
  {
    require(
      auctions[auctionId].currentBid < auctions[auctionId].reservePrice,
      "cancelAuction: Auction is at or above reserve"
    );
        require(
      block.timestamp <
        auctions[auctionId].firstBidTime + auctions[auctionId].duration,
      "Auction had completed"
    );
```

**Comment by IAmTurnipBoy** [comment]
Escalate for 1 USDC

This isn't an issue. If the auction isn't at reserve price and it's cancelled the lien holders getting fully repaid, whereas endAuction would result in the lien holders taking a loss. No harm in this an only benefit so I don't see a reason this should change

**Comment by sherlock-admin** [comment]
> Escalate for 1 USDC
> 
> This isn't an issue. If the auction isn't at reserve price and it's cancelled the lien holders getting fully repaid, whereas endAuction would result in the lien holders taking a loss. No harm in this an only benefit so I don't see a reason this should change

You've created a valid escalation for 1 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Evert0x** [comment]
Escalation accepted

**Comment by sherlock-admin** [comment]
> Escalation accepted

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
