### ISSUE TITLE
Rohan16 - Use safeTransferFrom() instead of transferFrom() for outgoing erc721 transfer

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-astaria-judging#293]
Rohan16

medium

# Use safeTransferFrom() instead of transferFrom() for outgoing erc721 transfer

## Summary
It is recommended to use safeTransferFrom() instead of transferFrom() when transferring ERC721s out of the vault.
## Vulnerability Detail

1. The transferFrom() method is used instead of safeTransferFrom(), which I assume is a gas-saving measure. I however argue that this isn’t recommended because:
- [OpenZeppelin’s documentation](https://docs.openzeppelin.com/contracts/4.x/api/token/erc721#IERC721-transferFrom-address-address-uint256-) discourages the use of transferFrom(); use safeTransferFrom() whenever possible
- The recipient could have logic in the onERC721Received() function, which is only triggered in the safeTransferFrom() function and not in transferFrom(). A notable example of such contracts is the Sudoswap pair:

## Impact
While unlikely because the recipient is the function caller, there is the potential loss of NFTs should the recipient is unable to handle the sent ERC721s.
[IERC721(underlyingAsset).transferFrom(address(this), releaseTo, assetId);](https://github.com/sherlock-audit/2022-10-astaria/blob/main/src/CollateralToken.sol#L223)
[nft.transferFrom(address(this), address(receiver), tokenId);](https://github.com/sherlock-audit/2022-10-astaria/blob/main/src/CollateralToken.sol#L176)
## Code Snippet

```solidity
nft.transferFrom(address(this), address(receiver), tokenId);
 IERC721(underlyingAsset).transferFrom(address(this), releaseTo, assetId);
```
## Tool used

Manual Review
## Recommendation
Use safeTransferFrom() when sending out the NFT from the vault.
```solidity 
- IERC721(_erc721Address).transferFrom(address(this), msg.sender, _id);
+ IERC721(_erc721Address).safeTransferFrom(address(this), msg.sender, _id);
```
Note that the vault would have to inherit the IERC721Receiver contract if the change is applied to Transfer.sol as well.

**Comment by IAmTurnipBoy** [comment]
Escalate for 1 USDC

This is actually a very bad idea. End auction uses _releaseToAddress to send NFT to winner. If winner is smart contract that doesn't implement ERC721 receiver then the NFT is forever lost and the auction can never be ended

**Comment by sherlock-admin** [comment]
> Escalate for 1 USDC
> 
> This is actually a very bad idea. End auction uses _releaseToAddress to send NFT to winner. If winner is smart contract that doesn't implement ERC721 receiver then the NFT is forever lost and the auction can never be ended

You've created a valid escalation for 1 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Evert0x** [comment]
Escalation accepted.

Should be low. Using safeTransferFrom has it's own quirks (reentrancy, contracts not able to receive if not implementing IERC721Receiver,..). I see this as a design decision by the sponsor/project team to use transferFrom(..) instead of safeTransferFrom(..)

**Comment by sherlock-admin** [comment]
> Escalation accepted.
> 
> Should be low. Using safeTransferFrom has it's own quirks (reentrancy, contracts not able to receive if not implementing IERC721Receiver,..). I see this as a design decision by the sponsor/project team to use transferFrom(..) instead of safeTransferFrom(..)

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
