### ISSUE TITLE
obront - liquidationAccountant can be claimed multiple times, losing a portion of all vault holders' funds

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-astaria-judging#47]
obront

high

# liquidationAccountant can be claimed multiple times, losing a portion of all vault holders' funds

## Summary

The `claim()` function in LiquidationAccountant.sol does not have any protection to ensure it is only called once. Since it is a public function, any user can call it repeatedly, which will arbitrarily decrease the vault's y-intercept, causing all vault depositors to lose a portion of their funds.

## Vulnerability Detail

The `claim()` function in LiquidationAccountant.sol is intended to be called after an auction is completed. The function does three things:
- Sends some portion of its balance to the `WITHDRAW_PROXY`
- Sends the rest of its balance to the vault
- Adjusts the vault's accounting, decreasing its y-intercept based on the amount of funds sent to the `WITHDRAW_PROXY` instead of the vault

Once the first two actions have been completed, there won't be any additional funds in the contract, so they won't perform any action.

However, the final action will have an impact, even if the `liquidationAccountant` has a balance of zero, because it decreases the y-intercept as follows:

```solidity
PublicVault(VAULT()).decreaseYIntercept(
  (expected - ERC20(underlying()).balanceOf(address(this))).mulDivDown(
    1e18 - withdrawRatio,
    1e18
  )
);
```
It uses the expected amount that the auctions should have earned and subtracts the current balance of the `liquidationAccountant`, and then adjusts it by the ratio of what will be sent back to the contract. 

When the balance of the contract is zero (after `claim()` has been called), it will decrease the y-intercept by `expected * (1e18 - withdrawRatio) / 1e18`, which will continue to reduce the y-intercept.

The arbitrary ability for any user to decrease a vault's y-intercept below the correct value risks the funds of all the holders of the vault's token. 

Imagine the following scenario:
- A user calls `claim()` repeatedly until the y-intercept reaches a very low (but non-zero) number
- Any future user calls `withdraw()` on the vault with X amount of assets 
- The `withdraw()` function calls `previewWithdraw()` to determine the number of shares that must be spent to withdraw the given amount of assets
- `previewWithdraw()` uses the formula `shares = assets * totalSupply() / totalAssets()`
- `totalAssets()` is calculated as `(slope * (block.timestamp) - last) + yIntercept`
- With a low y-intercept, this number will be extremely low, resulting in a high number of shares needed to retrieve a small amount of assets

## Impact

A malicious (or accidental) user can cause arbitrary decreases in the y-intercept of a vault once the auction is completed, which will cause all vault depositors to lose a portion of their funds.

## Code Snippet

https://github.com/sherlock-audit/2022-10-astaria/blob/main/src/LiquidationAccountant.sol#L62-L97

## Tool used

Manual Review

## Recommendation

- Add an extra variable to LiquidationAccountant.sol with a boolean `claimed`
- Update this variable after `claim()` has been called
- Check to ensure `!claimed` at the start of `claim()` to ensure it isn't called more than once

**Comment by IAmTurnipBoy** [comment]
Escalate for 1 USDC

Duplicate of #188, same underlying principle that function is permissionless

**Comment by sherlock-admin** [comment]
> Escalate for 1 USDC
> 
> Duplicate of #188, same underlying principle that function is permissionless

You've created a valid escalation for 1 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Evert0x** [comment]
Escalation accepted.

Same comment as #46

**Comment by sherlock-admin** [comment]
> Escalation accepted.
> 
> Same comment as #46 

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
