### ISSUE TITLE
rvierdiiev - AuctionHouse._handleIncomingPayment do not send interest to lien

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-astaria-judging#74]
rvierdiiev

high

# AuctionHouse._handleIncomingPayment do not send interest to lien

## Summary
AuctionHouse._handleIncomingPayment do not send interest to lien
## Vulnerability Detail
When someone creates bid on auction then `AuctionHouse._handleIncomingPayment` function is called. It then send payments to lien's vaults one by one. 

https://github.com/sherlock-audit/2022-10-astaria/blob/main/lib/astaria-gpl/src/AuctionHouse.sol#L281-L298
```solidity
      for (uint256 i = 0; i < liens.length; ++i) {
        uint256 payment;
        uint256 lienId = liens[i];

        ILienToken.Lien memory lien = LIEN_TOKEN.getLien(lienId);

        if (transferAmount >= lien.amount) {
          payment = lien.amount;
          transferAmount -= payment;
        } else {
          payment = transferAmount;
          transferAmount = 0;
        }

        if (payment > 0) {
          LIEN_TOKEN.makePayment(tokenId, payment, lien.position, payer);
        }
      }
```

The problem is that it uses `lien.amount` as value that should be sent as payment to LienToken. But it also should send interests, that were accrued for a lien.
## Impact
LienToken owner is underpaid with interests.
## Code Snippet
Provided above.
## Tool used

Manual Review

## Recommendation
Consider `lien.amount + LIEN_TOKEN.getInterest(lienId)` as full amount for LienToken payment.

**Comment by IAmTurnipBoy** [comment]
Escalate for 1 USDC

Invalid. Loans are paused and don't accumulate interest after the auction has been started.

Relevant Line:
https://github.com/sherlock-audit/2022-10-astaria/blob/7d12a5516b7c74099e1ce6fb4ec87c102aec2786/lib/astaria-gpl/src/AuctionHouse.sol#L73

**Comment by sherlock-admin** [comment]
> Escalate for 1 USDC
> 
> Invalid. Loans are paused and don't accumulate interest after the auction has been started.
> 
> Relevant Line:
> https://github.com/sherlock-audit/2022-10-astaria/blob/7d12a5516b7c74099e1ce6fb4ec87c102aec2786/lib/astaria-gpl/src/AuctionHouse.sol#L73

You've created a valid escalation for 1 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by rvierdiyev** [comment]
Aggree with this escalation.

**Comment by Evert0x** [comment]
Escalation accepted

**Comment by sherlock-admin** [comment]
> Escalation accepted

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
