### ISSUE TITLE
0x4141 - Reentrancy within flash action allows minting more collateral tokens

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-astaria-judging#78]
0x4141

high

# Reentrancy within flash action allows minting more collateral tokens

## Summary
There is no reentrancy protection for flash action, meaning the NFT can be deposited again.

## Vulnerability Detail
When someone takes out a flash action, he can redeposit the NFT as collateral (which will call `safeTransferFrom` and trigger `onERC721Received`), minting additional collateral token.

## Impact
More collateral tokens than intended are minted for a user.

## Code Snippet
https://github.com/sherlock-audit/2022-10-astaria/blob/main/src/CollateralToken.sol#L159

## Tool used

Manual Review

## Recommendation
Do not allow reentering, introduce a function for exiting the flash loan that does not trigger the `onERC721Received` logic.

**Comment by IAmTurnipBoy** [comment]
Escalate for 1 USDC

Not a dupe of 284 but also unfortunately invalid. OnRecieved doesn't mint another collateral token if one already exists.

Relevant line:
https://github.com/sherlock-audit/2022-10-astaria/blob/7d12a5516b7c74099e1ce6fb4ec87c102aec2786/src/CollateralToken.sol#L275

**Comment by sherlock-admin** [comment]
> Escalate for 1 USDC
> 
> Not a dupe of 284 but also unfortunately invalid. OnRecieved doesn't mint another collateral token if one already exists.
> 
> Relevant line:
> https://github.com/sherlock-audit/2022-10-astaria/blob/7d12a5516b7c74099e1ce6fb4ec87c102aec2786/src/CollateralToken.sol#L275

You've created a valid escalation for 1 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Evert0x** [comment]
Escalation accepted

**Comment by sherlock-admin** [comment]
> Escalation accepted

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
