### ISSUE TITLE
0x4141 - Vault: Unprotected mint / redeem function

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-astaria-judging#84]
0x4141

medium

# Vault: Unprotected mint / redeem function

## Summary
`Vault` only protects the `deposit` / `withdraw` functions.

## Vulnerability Detail
Within `Vault`, the `deposit` / `withdraw` functions are only callable by the owner. However, because the contracts inherits from ERC4626, there are also `mint` and `redeem` functions which are callable by anyone.

## Impact
Anyone can fund and exit the vault, which should not be possible for private vaults.

## Code Snippet
https://github.com/sherlock-audit/2022-10-astaria/blob/main/src/PublicVault.sol#L85

## Tool used

Manual Review

## Recommendation
Also overwrite the `mint` and `redeem` functions.

Duplicate of #176

**Comment by IAmTurnipBoy** [comment]
Escalate for 1 USDC

This is a dupe of plenty of others, seems to have been missed. This is the underlying issue in #117

**Comment by sherlock-admin** [comment]
> Escalate for 1 USDC
> 
> This is a dupe of plenty of others, seems to have been missed. This is the underlying issue in #117 

You've created a valid escalation for 1 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Evert0x** [comment]
Escalation accepted

**Comment by sherlock-admin** [comment]
> Escalation accepted 

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
