### ISSUE TITLE
rvierdiiev - LiquidationAccountant.claim function can be called any time

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-astaria-judging#89]
rvierdiiev

medium

# LiquidationAccountant.claim function can be called any time

## Summary
`LiquidationAccountant.claim` function can be called any time.
## Vulnerability Detail
Function `LiquidationAccountant.claim` should not be called once auction is ongoing.

https://github.com/sherlock-audit/2022-10-astaria/blob/main/src/LiquidationAccountant.sol#L66-L69
```solidity
    require(
      block.timestamp > finalAuctionEnd || finalAuctionEnd == uint256(0),
      "final auction has not ended"
    );
```

However this check will be always true, because `finalAuctionEnd` is not a timestamp, but a period and you can't compare it with `block.timestamp`.

This is how this value is provided

https://github.com/sherlock-audit/2022-10-astaria/blob/main/src/AstariaRouter.sol#L407-L410
```solidity
            LiquidationAccountant(accountant).handleNewLiquidation(
              lien.amount,
              COLLATERAL_TOKEN.auctionWindow() + 1 days
            );
```

And `COLLATERAL_TOKEN.auctionWindow()` is [period](https://github.com/sherlock-audit/2022-10-astaria/blob/main/src/CollateralToken.sol#L97).
## Impact
The check will always be true, so you can call `claim` even auction is not ended yet.
## Code Snippet
Provided above
## Tool used

Manual Review

## Recommendation
Use this in AstariaRouter when liquidate.
```solidity
            LiquidationAccountant(accountant).handleNewLiquidation(
              lien.amount,
              block.timestamp + COLLATERAL_TOKEN.auctionWindow() + 1 days
            );
```

**Comment by IAmTurnipBoy** [comment]
Escalate for 1 USDC

Duplicate of #175. Underlying issue in both is that it passes incorrect auction end time due to lack of block.timestamp

**Comment by sherlock-admin** [comment]
> Escalate for 1 USDC
> 
> Duplicate of #175. Underlying issue in both is that it passes incorrect auction end time due to lack of block.timestamp

You've created a valid escalation for 1 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Evert0x** [comment]
Escalation accepted

**Comment by sherlock-admin** [comment]
> Escalation accepted

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
